-- Generated by nwg-displays on 2026-07-23 at 12:06:52. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.0",
    position = "2912x1440",
    scale = 1.0
})
hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60.0",
    position = "0x0",
    scale = 1.5
})
hl.monitor({
    output = "DP-9",
    mode = "2560x1440@120.0",
    position = "2560x0",
    scale = 1.0
})
