-- Generated by nwg-displays on 2026-06-18 at 13:31:27. Do not edit manually.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x4146",
    mode = "3840x2400@60.0",
    position = "2876x1634",
    scale = 2.0
})
