-- Generated by nwg-displays on 2026-06-29 at 09:42:08. Do not edit manually.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x4146",
    mode = "3840x2400@60.0",
    position = "2836x1440",
    scale = 2.0
})
hl.monitor({
    output = "desc:Samsung Electric Company Odyssey G61SD HNAX901424",
    mode = "2560x1440@120.0",
    position = "2560x0",
    scale = 1.0
})
hl.monitor({
    output = "desc:ARZ ARZOPA-315",
    mode = "3840x2160@60.0",
    position = "0x0",
    scale = 1.5
})
